- CHANGELOG.md
- src/ui/activities/auth_activity/bookmarks.rs
Fixes #10 
Fixed wrong set_value for the text component while loading port.. Was using Unsigned instead of String.
> Issue 10 port number isnt correctly retrieved from the bookmarks.toml

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/filetransfer/ftp_transfer.rs
- src/filetransfer/scp_transfer.rs
Fixes #9 
To solve the issue, a module which converts paths from Windows to POSIX is necessary. This won't introduce any issue with windows because:
- Windows SCP server always support SFTP (and atm scp doesn't support windows at all)
- On FTP this doersn't introduce any issue
Changes:
- Added `path_slash` to dependencies
- Added `resolve` method to FTP/SCP file transfers to replace backslashes with slashes
> [BUG] Issue 9 some problems with symlinks hash and backslash characters

- CHANGELOG.md
- src/filetransfer/ftp_transfer.rs
- src/filetransfer/scp_transfer.rs
- src/filetransfer/sftp_transfer.rs
Fixes #18 
Currently the FTP file transfer, file are transferred using ASCII mode. This method corrupts binary files (and also text files tbh). The method should be changed to Binary.
List here your changes
- On connect method, the ftp client sets transfer type to `Binary`
- Error messages are now stringified using `to_string()`
> [BUG] every ftp transfer is made in ascii mode

- README.md
Hi! Thank you so much for `termscp`.
Just one nit: the two commands used in the README to install termscp using Homebrew can be folded into one command.
This:
```sh
brew install veeso/termscp/termscp
```
is equivalent to the two commands
```sh
brew tap veeso/termscp
brew install termscp
```
Thanks!
> One-liner for installing with Homebrew 😅

- CHANGELOG.md
- src/filetransfer/ftp_transfer.rs
- src/filetransfer/scp_transfer.rs
Fixes #17 
FTP file transfer:
- I still can't enter inside symlinks but it works with the Goto command
- I can now browse and enter inside the directories 
SFTP (Windows 10?):
- I can't enter inside symlinks at all and they are now considered like files
so the Goto command doesn't work
- I can enter the symlinks using the Goto command without your solution)
Changes performed:
- Fixed symlinks in SCP
> [BUG] Problems with symlinks

- CHANGELOG.md
- README.md
- src/host/mod.rs
- src/ui/activities/filetransfer_activity/session.rs
Fixes #23 
This PR introduces the removal of the file just created after an upload/download whenever the transfer fails. The feature is implemented in a way that prevents the client to try to remove a file which previously existed, but only when the write process has failed (so the file is corrupted).
List here your changes
- Introduced a `TransferErrorReason` enum as return for upload/download functions.
- Also fixed upload errors not being shown after an error.
> Remove created file if transfer failed

- CHANGELOG.md
- README.md
- docs/man.md
- src/ui/activities/filetransfer/actions/copy.rs
- src/ui/activities/filetransfer/actions/delete.rs
- src/ui/activities/filetransfer/actions/edit.rs
- src/ui/activities/filetransfer/actions/exec.rs
- src/ui/activities/filetransfer/actions/find.rs
- src/ui/activities/filetransfer/actions/mkdir.rs
- src/ui/activities/filetransfer/actions/mod.rs
- src/ui/activities/filetransfer/actions/newfile.rs
- src/ui/activities/filetransfer/actions/rename.rs
- src/ui/activities/filetransfer/actions/save.rs
- src/ui/activities/filetransfer/session.rs
- src/ui/activities/filetransfer/update.rs
- src/ui/activities/filetransfer/view.rs
- src/ui/components/file_list.rs
This PR adds the possilbity to operate on a group selection of files in explorers.
The implementation consists in:
- adding a combo key to push a file into the selection
- In actions iter over selection, instead of operating on one file
- File list now returns a list instead of an index if a selection is active, otherwise the highlighted element.
- If selection is empty, file list returns highlighted item as `One(Value::Usize)`
- If selection is not empty, file list returns  `Vec(Value::Usize)`with selected items
- Update clears the current selection
- If the user presses `<CTRL+A>` all elements get selected
- if the user presses `<M>` the item is pushed or popped to/from selection
- if the user presses `<L>` the selection is cleared
> Work on multiple files in explorers

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/ui/activities/auth/view.rs
- src/ui/activities/filetransfer/view.rs
- src/ui/activities/setup/view.rs
#39  - Help panels as scroll tables
Fixes #39 
- Changed help panel components to `Scrolltable` in order to allow scrolling.
- tui-realm 0.4.2
> Help panels as ScrollTable

- CHANGELOG.md
- src/ui/activities/filetransfer/actions/copy.rs
- src/ui/activities/filetransfer/actions/edit.rs
- src/ui/activities/filetransfer/session.rs
Fixes #37 
- New functions `send_one` and `recv_one` to transfer only one `FsFile` but mounting progress bar.
- Moved functions related to edit and tricky_copy from `session.rs` to action files.
> Fixed progress bar not visible when editing remote files

- CHANGELOG.md
- src/filetransfer/ftp_transfer.rs
Fixes #43 
- Change directory to file's parent dir, when removing files.
> fixed recursive remove FTP

- src/filetransfer/ftp_transfer.rs
Fixes #44 
- Use destination path in `rename`
> Ftp: cant move files to other directories

- CHANGELOG.md
- src/host/mod.rs
- src/ui/activities/auth/misc.rs
- src/ui/activities/auth/mod.rs
- src/ui/activities/auth/update.rs
- src/ui/activities/auth/view.rs
Fixes #36 
- Absolute layout size when known
- When window is too small (height lower than 24) an error message will be displayed on the auth activity
> Window too small error message

- CHANGELOG.md
- src/fs/mod.rs
- src/ui/activities/filetransfer/actions/copy.rs
- src/ui/activities/filetransfer/actions/edit.rs
- src/ui/activities/filetransfer/actions/find.rs
- src/ui/activities/filetransfer/actions/mod.rs
- src/ui/activities/filetransfer/actions/save.rs
- src/ui/activities/filetransfer/mod.rs
- src/ui/activities/filetransfer/session.rs
Fixes #38 
- TransferPayload entity to describe the payload of a transfer in session.rs
- Single function to send and receive file entries
- Calculate transfer size based on entity
> Fixed transfer size when sending multiple entries

- CHANGELOG.md
- src/ui/activities/filetransfer/actions/copy.rs
Fixes #58 
- Umount wait popup before performing tricky copy. The wait popup caused the ui to break when using tricky copy.
> Fix: When copying files with tricky copy, the upper progress bar shows no text

- CHANGELOG.md
- docs/de/man.md
- docs/es/man.md
- docs/fr/man.md
- docs/it/man.md
- docs/man.md
- docs/zh-CN/man.md
- src/config/params.rs
- src/config/serialization.rs
- src/filetransfer/builder.rs
- src/system/config_client.rs
- src/ui/activities/auth/components/bookmarks.rs
- src/ui/activities/setup/components/config.rs
- src/ui/activities/setup/components/mod.rs
- src/ui/activities/setup/config.rs
- src/ui/activities/setup/mod.rs
- src/ui/activities/setup/update.rs
- src/ui/activities/setup/view/setup.rs
Fixes #77
- Added `ssh_config` parameter to configuration
- Read ssh configuration file when connecting to SFTP/SCP server
> SSH configuration path

- src/ui/activities/filetransfer/components/misc.rs
The 'Delete' shortcut was listed as 'Make dir', probably a copy paste oversight from the previous item.
> Fix shortcut description in footer

- .gitignore
- dist/build/macos.sh
- install.sh
Fixes #95 
- Added to macos.sh build script the build for Apple M1 chip.
> macos arm64 build

- CHANGELOG.md
- src/explorer/formatter.rs
- src/utils/fmt.rs
- src/utils/string.rs
Fixes #104 
- Use unicode width to get string length in fmt_name and fmt_path
- safe substring function to get filenames
> Fixed termscp panics when displaying long non-ascii filenames

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/config/serialization.rs
- src/system/sshkey_storage.rs
Fixes #126 
- Bump remotefs-ssh 0.1.3
- Optimized ssh key storage
> 126 new feature termscp doesnt use id rsa default ssh private key to authenticate to sftp scp endpoint

- CHANGELOG.md
- src/config/params.rs
- src/system/config_client.rs
Fixes #130 
- SSH configuration path is now `~/.ssh/config` by default
> SSH configuration path is not `~/.ssh/config` by default

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/host/mod.rs
- src/ui/activities/filetransfer/session.rs
Fixes #133 
- **Transfers optimized**:
- If local/remote file have the same "last modification time" (`mtime`), the file is not transferred
- When the file is exchanged, all times attributes are set (if supported by the protocol)
> Optimize transfers

- CHANGELOG.md
- src/config/params.rs
- src/system/config_client.rs
- src/system/environment.rs
Fixes #150
- init_config_dir: use `create_dir_all` instead of `create_dir` in order to create `.config/` if it doesn't exist yet.
- before setting default ssh config path; check wheter it actually exists
> issue 150: some issues with configuration

- Cargo.toml
Fixes #154
- bump remotefs-ssh to 0.1.5
> bump remotefs-ssh to 0.1.5

- Cargo.lock
- Cargo.toml
Fixes #166
- remotefs-ssh 0.1.6
> fix: relative paths windows

- docs/de/man.md
- docs/es/man.md
- docs/fr/man.md
- docs/it/man.md
- docs/man.md
- docs/zh-CN/man.md
- src/activity_manager.rs
- src/config/serialization.rs
- src/config/themes.rs
- src/filetransfer/params.rs
- src/host/mod.rs
- src/main.rs
- src/support.rs
- src/system/auto_update.rs
- src/system/bookmarks_client.rs
- src/system/environment.rs
- src/system/logging.rs
- src/ui/activities/auth/mod.rs
- src/ui/activities/filetransfer/lib/transfer.rs
- src/ui/activities/setup/mod.rs
- src/utils/crypto.rs
- src/utils/file.rs
- src/utils/fmt.rs
- src/utils/parser.rs
- src/utils/path.rs
- src/utils/test_helpers.rs
Fixes #176 
- Log files are now written to cache dir
> debug log belongs in cache directory not config directory

- CHANGELOG.md
- src/ui/activities/filetransfer/session.rs
Fixes #153
- show a loading popup when loading directory content
> 153 feature request progress indicator for listing large folders

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/filetransfer/builder.rs
- src/system/sshkey_storage.rs
Fixes #173
- allow unknown fields in ssh2 configuration file
- remotefs-ssh 0.2
- ssh2-config 0.2
> allow unknown fields in ssh2 configuration file

- README.md
- dist/build/freebsd.sh
- dist/build/linux-aarch64.sh
- dist/build/linux-x86_64.sh
- docs/de/README.md
- docs/es/README.md
- docs/fr/README.md
- docs/it/README.md
- docs/zh-CN/README.md
- install.sh
- site/html/get-started.html
- site/html/updates.html
Fixes #174 
- Added brew to install script
- Removed `termscp-m1` formula. Everything has been merged in a single formula.
> Brew Linux support

- CHANGELOG.md
- src/activity_manager.rs
- src/filetransfer/builder.rs
- src/filetransfer/params.rs
- src/system/sshkey_storage.rs
- src/ui/activities/filetransfer/view.rs
- src/utils/mod.rs
- src/utils/parser.rs
- src/utils/ssh.rs
Fixes #175
- If a ssh key is found in ssh key storage in activity manager, don't prompt for password.
> Don't prompt for password if a ssh key is set for that host

- build.rs
- src/filetransfer/builder.rs
- src/ui/activities/setup/actions.rs
- src/utils/parser.rs
Fixes #205
- Added `smb_windows` cfg build to disable smb on Windows if feature is disabled
> added cfg smb-windows to be able to disable SMB on windows

- CHANGELOG.md
- src/config/serialization.rs
- src/explorer/mod.rs
- src/filetransfer/builder.rs
- src/system/mod.rs
- src/ui/activities/filetransfer/actions/mod.rs
- src/ui/activities/filetransfer/mod.rs
Fixes #215
- Override connection params port if a port is specified for host in ssh config file
> [BUG] - termscp not respecting port in ssh config

- docs/man.md
Fixes a non-tagged issue.
Fixed formatting within the keybinding table. Explicitly, I escaped the pipes (`|`).
> Fixed formatting

- CHANGELOG.md
- README.md
- docs/de/man.md
- docs/es/man.md
- docs/fr/man.md
- docs/it/man.md
- docs/man.md
- docs/zh-CN/man.md
- src/cli_opts.rs
- src/config/mod.rs
- src/host/mod.rs
- src/main.rs
- src/system/config_client.rs
- src/system/sshkey_storage.rs
- src/ui/activities/setup/view/mod.rs
- src/utils/path.rs
Fixes #233
- Added subcommands to replace options for config, theme and update
> 233 feature request subcommands

- README.md
- install.sh
- site/html/get-started.html
- site/lang/en.json
`termscp` is now an official Arch Linux package: <https://archlinux.org/packages/extra/x86_64/termscp/>
This PR updates the documentation about this change.
wait for a _project maintainer_ to fulfill this section...
> docs: update Arch Linux instructions

- README.md
- docs/de/README.md
- docs/es/README.md
- docs/fr/README.md
- docs/it/README.md
- docs/ptbr/README.md
- docs/ptbr/man.md
- docs/zh-CN/README.md
Fixes #245
Correcting issue #245, providing a Brazilian Portuguese translation of README.md and man.md (manual). Additionally, adding the PT-BR translation link to the other available translations.
Changes:
- Added translation of README.md and man.md (Manual) in PT-BR.
- Change in other translations, providing the link to the translation in PT-BR (tag a, the image of Brazil).
by. harturalcantara
> Adding Brazilian Portuguese translation

- src/cli_opts.rs
Fixes wrong help text for `update` subcommand introduced in 679a8297442f17d8adc9428aca304c8892d0eee9
> fix: correct help text for update subcommand

- CHANGELOG.md
- src/ui/activities/filetransfer/components/transfer/file_list.rs
Fixes #241
- increment index by one after selecting a file; no rewind
> fix: Jump to next entry after select

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/filetransfer/builder.rs
Fixes #226
- Updated remotefs-ssh to 0.3
- Setup ssh-agent to All in SshOpts
> feat: ssh-agent

- Cargo.lock
Bump rustls to v0.21.12 so the project uses ring 0.17, which brings extra platform support e.g. RISC-V.
> chore: bump ring to 0.17

- src/ui/activities/filetransfer/mod.rs
Fixed `empty-line-after-doc-comments` error added into the default warning in Clippy 1.83.
Failed workflow log:
https://github.com/veeso/termscp/actions/runs/12526546042/job/34939229766#step:7:332
```
error: empty line after doc comment
--> src/ui/activities/filetransfer/mod.rs:357:1
|
357 | / /**
358 | |  * Activity Trait
359 | |  * Keep it clean :)
360 | |  * Use methods instead!
361 | |  */
362 | |
| |_
363 |   impl Activity for FileTransferActivity {
|   -------------------------------------- the comment documents this implementation
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_doc_comments
= note: `-D clippy::empty-line-after-doc-comments` implied by `-D warnings`
= help: to override `-D warnings` add …
```
> fix: clippy error

- CHANGELOG.md
- dist/build/macos.sh
- src/filetransfer/remotefs_builder.rs
- src/system/sshkey_storage.rs
I think I fixed the id_rsa/id_ed25519 SSH auth issue on Mac and now termscp should respect the key-based authentication, just like the regular ssh user@hostname, without the need for any ssh agents.
Original Author @czekaj but for some reasons I was not able to push to his fork.
> Fix SSH auth with id keys
